### ISSUE TITLE
Calculs à appliquer version 0.8, nombre d'éléments dans le groupe.

### ISSUE THREAD

**Issue by BalamSal** [koumoul-dev/data-fair-charts#3]
Dans la version 0.6 de charts, dans les calculs à appliquer on peut calculer le nombre d'éléments dans le groupe.

Dans la version 0.8 de charts, cette option a disparu. Dans Préparation des données > Calcul à effectué > Type de calcul, l’option n'est plus disponible.

**Comment by albanm** [comment]
Parce que ça correspond à l'autre type de graphique. Un truc genre "grouper les lignes et les compter" au lieu de "grouper les lignes et effectuer un calcul".

**Comment by BalamSal** [comment]
En effet, il fallait passer par un autre type graphique.
